### ISSUE TITLE
Setting global variables in config files not working

### ISSUE THREAD

**Issue by tyssen** [focuslabllc/ee-master-config#41]
I have `$env_globals['global:basepath'] = 'http://xxxxxx.com/';` in config.local.php but in my templates, I get `{global:basepath}` output instead of the value.

This is under a MAMP set-up on my Mac. Everything else works fine. Is there something else I'm missing?

**Comment by ajgaunt** [comment]
Try $env_global['global:base path'] instead of the plural.

- Andy

**Comment by tyssen** [comment]
Ah, that did it. Thanks. :)
